# Generated by Django 5.0.1 on 2024-01-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=101)),
                ('file_sound', models.FileField(blank=True, null=True, upload_to='sounds/')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('verb', models.CharField(default='', max_length=101)),
            ],
        ),
    ]
