# Generated by Django 5.0.1 on 2024-01-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=101)),
                ('class_name', models.CharField(choices=[], default='', max_length=101)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('animal.animal',),
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('animal.animal',),
        ),
    ]
