# Generated by Django 5.0.1 on 2024-01-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='file_sound',
            field=models.FileField(blank=True, null=True, upload_to='sounds/'),
        ),
    ]
